FROM mattiasegly/node-image:bullseye-386 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	build-essential \
&& rm -rf /var/lib/apt/lists/* \
&& update-alternatives --install /usr/bin/python python /usr/bin/python3 1

SHELL ["/bin/bash", "--login", "-c"]
RUN npm install --global --only=production pouchdb-server

FROM mattiasegly/node-image:bullseye-386

COPY --from=builder /usr/local/nvm/ /usr/local/nvm/

VOLUME /data
WORKDIR /data
EXPOSE 8080

CMD ["pouchdb-server", "-o", "0.0.0.0", "-p", "8080"]